var test = new Vue({
    el: '#test',
    mounted: function() {
    	$('#q1').show();
    	$('#q2').hide();
    	$('#q3').hide();
    	$('#q4').hide();
    	$('#q5').hide();
    	$('#q6').hide();
    	$('#q7').hide();
    	$('#q8').hide();
        $('#q9').hide();
        $('#q10').hide();
        $('#q11').hide();
        $('#q12').hide();
        $('#q13').hide();
        $('#q14').hide();
        $('#q15').hide();
        $('#q16').hide();
        $('#q17').hide();
        $('#q18').hide();
        $('#q19').hide();
        $('#q20').hide();
        $('#q21').hide();
    },
    methods: {
    	prev1: function(){ //1번째 이전(1->1)
    		alert('첫 번째 질문입니다.');
    	},
    	prev2: function(){ //2번째 이전(2->1)
    		$('#q1').show();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev3:function(){ //3번째 이전(3->2)
    		$('#q1').hide();
    		$('#q2').show();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev4: function(){ //4번째 이전(4->3)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').show();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev5: function(){ //5번째 이전 (5->4)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').show();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev6: function(){ //6번째 이전 (6->5)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').show();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev7: function(){ //7번째 이전(7->6)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').show();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev8: function(){//8번째 이전(8->7)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').show();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev9: function(){ //9번째 이전(9->8)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').show();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev10: function(){ //10번째 이전(10->9)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').show();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev11: function(){ //11번째 이전(11->10)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').show();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev12: function(){ //12번째 이전(12->11)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').show();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev13: function(){ //13번째 이전(13->12)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').show();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev14: function(){ //14번째 이전(14->13)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').show();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev15: function(){ //15번째 이전(15->14)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').show();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev16: function(){ //16번째 이전(16->15)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').show();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev17: function(){ //17번째 이전(17->16)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').show();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev18: function(){ //18번째 이전(18->17)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').show();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev19: function(){ //19번째 이전(19->18)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').show();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev20: function(){ //20번째 이전(20->19)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').show();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	prev21: function(){ //21번째 이전(21->20)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').show();
            $('#q21').hide();
    	},
    	next1: function(){ //1번째 다음(1->2)
    		$('#q1').hide();
    		$('#q2').show();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next2: function(){ //2번째 다음(2->3)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').show();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next3: function(){ //3번째 다음(3->4)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').show();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next4: function(){ //4번째 다음(4->5)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').show();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next5: function(){ //5번째 다음(5->6)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').show();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next6: function(){//6번째 다음(6->7)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').show();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next7: function(){//7번째 다음(7->8)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').show();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next8: function(){ //8번째 다음(8->9)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').show();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next9: function(){ //9번째 다음(9->10)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').show();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next10: function(){ //10번째 다음(10->11)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').show();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next11: function(){ //11번째 다음(11->12)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').show();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next12: function(){ //12번째 다음(12->13)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').show();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next13: function(){ //13번째 다음(13->14)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').show();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next14: function(){ //14번째 다음(14->15)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').show();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next15: function(){ //15번째 다음(15->16)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').show();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next16: function(){ //16번째 다음(16->17)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').show();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next17: function(){ //17번째 다음(17->18)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').show();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next18: function(){ //18번째 다음(18->19)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').show();
            $('#q20').hide();
            $('#q21').hide();
    	},
    	next19: function(){ //19번째 다음(19->20)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').show();
            $('#q21').hide();
    	},
    	next20: function(){ //20번째 다음(20->21)
    		$('#q1').hide();
    		$('#q2').hide();
    		$('#q3').hide();
    		$('#q4').hide();
    		$('#q5').hide();
        	$('#q6').hide();
        	$('#q7').hide();
        	$('#q8').hide();
            $('#q9').hide();
            $('#q10').hide();
            $('#q11').hide();
            $('#q12').hide();
            $('#q13').hide();
            $('#q14').hide();
            $('#q15').hide();
            $('#q16').hide();
            $('#q17').hide();
            $('#q18').hide();
            $('#q19').hide();
            $('#q20').hide();
            $('#q21').show();
    	},
    	next21: function(){
    		alert('test');
    	}
    }
});

function fn_test(){
	var form = document.form1;
	
	form.method="post";
	form.action="test.do";
	form.submit();
	
}


